<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE party [
  <!ELEMENT party (gast+)>
  <!ATTLIST party datum CDATA #REQUIRED>
  <!ELEMENT gast (getraenk+, zustand?)>
  <!ATTLIST gast name CDATA #REQUIRED>
  <!ELEMENT getraenk (#PCDATA)>
  <!ELEMENT zustand EMPTY>
  <!ATTLIST zustand ledig CDATA #REQUIRED
                    nuechtern CDATA #REQUIRED>
]>
<party datum="31.12.01">
	<gast name="Albert Angsthase">
		<getraenk>Wein</getraenk>
		<getraenk>Bier</getraenk>
		<zustand ledig="true" nuechtern="false" />
	</gast>
	<gast name="Martina Mutig">
		<getraenk>Apfelsaft</getraenk>
		<zustand ledig="true" nuechtern="true" />
	</gast>
	<gast name="Zacharias Zottelig">
		<getraenk>Martini</getraenk>
		<zustand ledig="false" nuechtern="false" />
	</gast>
</party>
