=== b-eyselein/it4all/conf/resources/xml/exerciseSchema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#", 
	"type": "array", 
	"items": {
		"type": "object", 
		"properties": {
			"id": {
				"type": "integer", 
				"minimum": 1
			}, 
			"title": {
				"type": "string"
			}, 
			"exerciseType": {
				"enum": [
					"DTD_XML", 
					"XSD_XML", 
					"XML_DTD", 
					"XML_XSD"
				]
			}, 
			"fixedStart": {
				"type": "string"
			}, 
			"referenceFileName": {
				"type": "string"
			}, 
			"text": {
				"type": "string"
			}
		}, 
		"required": [
			"id", 
			"title", 
			"exerciseType", 
			"fixedStart", 
			"referenceFileName", 
			"text"
		]
	}, 
	"minItems": 1, 
	"uniqueItems": true
}

=== b-eyselein/it4all/conf/resources/xml/exercises.json
[
	{
		"id": 1, 
		"title": "Party", 
		"exerciseType": "XML_DTD", 
		"fixedStart": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE party SYSTEM \"party.dtd\">", 
		"referenceFileName": "party", 
		"text": "Erstellen Sie zu dieser Document Type Definition ein passendes XML-Dokument."
	}, 
	{
		"id": 2, 
		"title": "Vorlesung", 
		"exerciseType": "XML_DTD", 
		"fixedStart": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE lecture SYSTEM \"lecture.dtd\">", 
		"referenceFileName": "lecture", 
		"text": "Erstellen Sie zu dieser DTD ein passendes XML-Dokument."
	}, 
	{
		"id": 3, 
		"title": "Fr端hst端ck", 
		"exerciseType": "DTD_XML", 
		"fixedStart": "", 
		"referenceFileName": "breakfast", 
		"text": "Erstellen Sie f端r dieses Dokument eine passende Document Type Definition."
	}, 
	{
		"id": 4, 
		"title": "Krankenhaus", 
		"exerciseType": "XML_DTD", 
		"fixedStart": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE krankenhaus SYSTEM \"hospital.dtd\">", 
		"referenceFileName": "hospital", 
		"text": "Erstellen Sie zu dieser DTD ein passendes XML-Dokument."
	}, 
	{
		"id": 5, 
		"title": "Bibliothek", 
		"exerciseType": "DTD_XML", 
		"fixedStart": "", 
		"referenceFileName": "bibliothek", 
		"text": "Erstellen Sie f端r dieses Dokument eine passende Document Type Definition."
	}
]
