=== b-eyselein/it4all/modules/xml/conf/resources/party.dtd
<!ELEMENT party (gast)*>
<!ATTLIST party datum CDATA #REQUIRED>
<!ELEMENT gast (getraenk*, zustand?)>
<!ATTLIST gast name CDATA #REQUIRED>
<!ELEMENT getraenk (#PCDATA)>
<!ELEMENT zustand EMPTY>
<!ATTLIST zustand ledig CDATA #IMPLIED nuechtern CDATA #IMPLIED>

=== b-eyselein/it4all/modules/xml/test/resources/partyWarning.xml
<?xml version="1.0" ?>
<!DOCTYPE party SYSTEM "party.dtd">
<party datum="31.12.01">
    <gast name="Albert Angsthase">
        <getraenk>Wein</getraenk>
        <getraenk>Bier</getraenk>
        <zustand ledig="true" nuechtern="false"/>
    </gast>
    <gast name="Martina Mutig">
        <zustand ledig="true" nuechtern="true"/>
        <getraenk>Apfelsaft</getraenk>
    </gast>
    <gast name="Zacharias Zottelig"></gast>
</party>

=== b-eyselein/it4all/modules/xml/test/resources/partyWrongTag.xml
<?xml version="1.0" ?>
<!DOCTYPE party SYSTEM "party.dtd">
<party datum="31.12.01">
    <guest name="Albert Angsthase">
        <getraenk>Wein</getraenk>
        <getraenk>Bier</getraenk>
        <zustand ledig="true" nuechtern="false"/>
    </guest>
    <gast name="Martina Mutig">
        <getraenk>Apfelsaft</getraenk>
        <zustand ledig="true" nuechtern="true"/>

    </gast>
    <gast name="Zacharias Zottelig"></gast>
</party>
